export const envs = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL,
  HOMEPAGE: import.meta.env.VITE_HOMEPAGE,
  AZURE_REDIRECT_URI: import.meta.env.VITE_AZURE_REDIRECT_URI,
  VITE_AZURE_CLIENT_ID: import.meta.env.VITE_AZURE_CLIENT_ID,
  VITE_AZURE_AUTORITY: import.meta.env.VITE_AZURE_AUTORITY,
  VITE_AZURE_REDIRECT_URI: import.meta.env.VITE_AZURE_REDIRECT_URI,
}